name: Create Release Tag

on:
  push:
    tags:
      - '@starter/docs*' # Push events to matching @starter/docs*

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release for Tag
        id: release_tag
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          draft: true
          body: |
            > Please refer to [CHANGELOG.md](https://github.com/tagtwp/documentation-starter/tree/master/docs/CHANGELOG.md) for details.